name: 🚀 Feature Request
description: Suggest an idea, feature, or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an idea.

        Before submitting, please make sure that there's no issue already open for this suggestion.
        Please note that this is not a guarantee your feature will be accepted.
        For best results, maybe consult the [Discord](https://discord.gg/xQnwhuktG6) before making an issue.
  - type: textarea
    attributes:
      label: What is the problem this feature would solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the feature you are proposing to solve the problem?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?